<a href="https://colab.research.google.com/github/hans8854/pytorch_test/blob/main/numpy%E5%AF%A6%E7%8F%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

In [6]:
N, D_in, H, D_out = 64, 1000, 100, 10

#隨機創建一些訓練數據
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for it in range(500):
  # Forward pass
  h = x.dot(w1) # N * H
  h_relu = np.maximum(h, 0) # N * H
  y_pred = h_relu.dot(w2) # N * D_out

  #compute loss
  loss = np.square(y_pred - y).sum()
  print(it, loss)

  #Backward pass
  #compute the gradient
  # y = ax + b
  # dy / dx = a
  # dy / da = x
  grad_y_pred = 2.0 * (y_pred - y )
  grad_w2 = h_relu.T.dot(grad_y_pred)
  grad_h_relu = grad_y_pred.dot(w2.T)
  grad_h = grad_h_relu.copy()
  grad_h[h<0] = 0
  grad_w1 = x.T.dot(grad_h)
  #update weights of w1 and w2
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2


0 21047232.44501496
1 17768214.725192383
2 17384692.842187226
3 17994277.728233803
4 18160222.01459025
5 16871123.345734015
6 13976878.259129021
7 10329590.79829985
8 6917017.370083485
9 4358217.361070765
10 2687155.5242469427
11 1683905.5429883692
12 1101642.9937867108
13 763656.8279653557
14 561813.6994969457
15 435650.740534693
16 351966.3513073393
17 293014.89589319774
18 249093.06460947538
19 214743.51934813883
20 186947.90702937217
21 163873.2966218869
22 144448.5065508003
23 127869.59787125625
24 113560.17810923117
25 101124.9264627897
26 90252.32269294011
27 80735.49695158374
28 72348.58483903718
29 64940.051438294686
30 58384.73033189214
31 52570.5413317464
32 47402.78350037568
33 42796.06464104614
34 38682.835624347346
35 35006.928129466476
36 31715.951749464046
37 28767.204557306573
38 26115.44297547633
39 23730.980304339704
40 21583.304437607854
41 19647.32504191206
42 17901.494658323118
43 16323.058510385215
44 14894.545506003988
45 13600.986824480575
46 12428.769191680236

input 64, dimension 10維, hiden layer100維, 輸出10維

*   h = W_1X
*   a = max(0,h)
*   y_hat = W_2A





In [7]:
x

array([[ 1.05919669,  0.07113402, -2.03306471, ..., -1.21520003,
         0.37719864, -0.67541966],
       [-1.03297443, -0.77313845, -0.82435148, ...,  1.89997406,
        -0.8999344 ,  0.32798768],
       [ 1.06481935,  0.30444992,  1.35875659, ..., -1.74644885,
        -1.36549069, -0.71543064],
       ...,
       [ 0.90279429,  0.18236425, -0.07316246, ..., -0.57895163,
         2.06112284, -0.62786588],
       [-0.27995671,  0.42571184,  0.62596381, ...,  1.81871133,
        -2.1673964 ,  0.54723578],
       [ 0.45679073,  0.3080034 , -0.14603563, ...,  0.77715503,
        -0.02317651, -1.72492927]])

In [9]:
  h = x.dot(w1) # N * H
  h_relu = np.maximum(h, 0) # N * H
  y_pred = h_relu.dot(w2) # N * D_out

In [11]:
y_pred - y

array([[ 4.80438014e-07, -1.83965129e-06,  1.16126390e-07,
        -6.15046629e-06,  5.94865053e-06, -3.77769294e-06,
         2.44604280e-06,  2.14655436e-06,  3.14052944e-06,
        -5.02583330e-06],
       [ 1.05732503e-05, -5.13008777e-06,  1.39513785e-05,
        -1.22975669e-05,  3.18192644e-05, -1.23162373e-05,
         3.15291913e-06,  1.02155675e-05,  8.36306756e-06,
        -1.60961894e-05],
       [ 2.35103862e-06, -3.93865206e-06,  2.78855316e-06,
        -4.19644647e-06,  1.18413523e-05, -5.09090930e-06,
         5.16469827e-06,  5.78313381e-06,  3.66880883e-06,
        -6.51733451e-06],
       [ 2.80897765e-06, -1.52807128e-07, -4.88023974e-07,
         1.11148357e-06,  1.76903988e-06,  1.18588547e-07,
         6.84761074e-07,  8.05711055e-07, -4.19814456e-07,
        -5.88018349e-07],
       [ 7.92495196e-06, -9.71140211e-06,  6.85894507e-06,
        -7.75885722e-06,  1.77465534e-05, -9.32376520e-06,
         5.70848230e-06,  7.14627593e-06,  7.93726870e-06,
        -1.

In [8]:
y

array([[-1.4273267 ,  0.83320644, -0.32601741,  0.92974528,  1.36627367,
         0.05080788,  1.0403592 , -1.33162891, -0.21919757,  1.73814064],
       [-0.55760061, -0.23568743, -0.49497438,  0.0070339 , -0.01267485,
         0.8814321 , -1.34163768,  0.37969833,  0.97074497, -1.50765958],
       [-1.37748647, -0.1626403 , -1.222668  , -1.83951345,  0.83677149,
         2.65543075,  0.32745036,  0.05206815,  1.0242805 , -0.61652511],
       [ 1.51196182, -0.74806355,  0.22946631, -0.58856846,  0.08246245,
        -0.70553323, -1.96361275,  1.2722481 ,  0.42728174,  0.18496758],
       [ 0.71404033,  0.71842481,  0.0294637 ,  0.09295476, -0.66026435,
         0.61384573, -1.12138657,  1.38353561,  0.69985647, -1.54040365],
       [-1.19139777,  0.99156205,  1.2579349 , -1.58271786,  0.14544608,
         0.85728809, -1.57304843,  0.77507161,  1.86498481,  0.22399471],
       [-0.06601737,  0.78320314, -0.6086617 ,  0.28510474, -0.46198933,
         0.69674965,  1.0084822 ,  0.15337778