<a href="https://colab.research.google.com/github/hans8854/pytorch_test/blob/main/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [2]:
x = torch.empty(5,3)

tensor([[2.1765e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

In [3]:
x = torch.rand(5,3)

tensor([[0.0301, 0.8686, 0.6756],
        [0.3153, 0.7108, 0.1005],
        [0.3666, 0.3988, 0.2619],
        [0.0995, 0.1148, 0.0857],
        [0.4204, 0.1027, 0.4157]])

In [10]:
x = torch.zeros(5,3,dtype=torch.long)
x = torch.zeros(5,3).long()
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x.dtype

torch.int64

In [12]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [13]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
x = torch.randn_like(x, dtype= torch.float)
x

tensor([[-1.6479, -0.8950, -1.2141],
        [ 0.8702,  1.2261,  0.2503],
        [ 0.1235,  0.0886, -1.7289],
        [-1.1172,  0.2244,  0.2071],
        [-0.3974,  0.3236, -0.8299]])

In [15]:
x.shape

torch.Size([5, 3])

In [23]:
y = torch.rand(5,3)
y

tensor([[0.3224, 0.7089, 0.4442],
        [0.5065, 0.0586, 0.6788],
        [0.2603, 0.4663, 0.2923],
        [0.4713, 0.9158, 0.1437],
        [0.1924, 0.2694, 0.7338]])

In [25]:
x + y

tensor([[-1.3255, -0.1861, -0.7699],
        [ 1.3766,  1.2847,  0.9291],
        [ 0.3838,  0.5550, -1.4366],
        [-0.6459,  1.1402,  0.3508],
        [-0.2050,  0.5930, -0.0962]])

In [24]:
torch.add(x, y)

tensor([[-1.3255, -0.1861, -0.7699],
        [ 1.3766,  1.2847,  0.9291],
        [ 0.3838,  0.5550, -1.4366],
        [-0.6459,  1.1402,  0.3508],
        [-0.2050,  0.5930, -0.0962]])

In [26]:
y.add_(x)
y

tensor([[-1.3255, -0.1861, -0.7699],
        [ 1.3766,  1.2847,  0.9291],
        [ 0.3838,  0.5550, -1.4366],
        [-0.6459,  1.1402,  0.3508],
        [-0.2050,  0.5930, -0.0962]])

In [29]:
y[1:,1:]

tensor([[ 1.2847,  0.9291],
        [ 0.5550, -1.4366],
        [ 1.1402,  0.3508],
        [ 0.5930, -0.0962]])

In [33]:
x= torch.rand(4,4)
x
y= x.view(16)
z= x.view(-1,2)
z

tensor([[0.1591, 0.4318],
        [0.5475, 0.2412],
        [0.4274, 0.1890],
        [0.3448, 0.5525],
        [0.2092, 0.8432],
        [0.4688, 0.2634],
        [0.1024, 0.7777],
        [0.8538, 0.0673]])

In [35]:
x = torch.rand(1)
x

tensor([0.5811])

In [40]:
# dir(x)

In [39]:
x.data
x.grad
x.item()

0.5811089873313904

In [42]:
z.transpose(1,0)

tensor([[0.1591, 0.5475, 0.4274, 0.3448, 0.2092, 0.4688, 0.1024, 0.8538],
        [0.4318, 0.2412, 0.1890, 0.5525, 0.8432, 0.2634, 0.7777, 0.0673]])

In [43]:
a = torch.ones(5)
a 

tensor([1., 1., 1., 1., 1.])

In [44]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [45]:
b[0] = 2
b

array([2., 1., 1., 1., 1.], dtype=float32)

In [46]:
a

tensor([2., 1., 1., 1., 1.])

In [49]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)

[2. 2. 2. 2. 2.]


In [50]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [7]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  y = torch.ones_like (x,device=device)
  x = x.to(device)
  x = x + y
  print(x)
  print(x.to('cpu', torch.double))

SyntaxError: ignored

In [ ]:
y..to('cpu').data.numpy[]
y.cpu().data.numpy( )