<a href="https://colab.research.google.com/github/hans8854/pytorch_test/blob/main/torch%E5%AF%A6%E7%8F%BE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

In [12]:
N, D_in, H, D_out = 64, 1000, 100, 10

#隨機創建一些訓練數據
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H)
w2 = torch.randn(H, D_out)

learning_rate = 1e-6
for it in range(500):
  # Forward pass
  h = x.mm(w1) # N * H
  h_relu = h.clamp(min=0) # N * H
  y_pred = h_relu.mm(w2) # N * D_out

  #compute loss
  loss = (y_pred - y).pow(2).sum().item()
  print(it, loss)

  #Backward pass
  #compute the gradient
  # y = ax + b
  # dy / dx = a
  # dy / da = x
  grad_y_pred = 2.0 * (y_pred - y )
  grad_w2 = h_relu.t().mm(grad_y_pred)
  grad_h_relu = grad_y_pred.mm(w2.t())
  grad_h = grad_h_relu.clone()
  grad_h[h<0] = 0
  grad_w1 = x.t().mm(grad_h)
  #update weights of w1 and w2
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2


0 36040844.0
1 39729556.0
2 50368672.0
3 55342828.0
4 44002236.0
5 22111912.0
6 8116575.0
7 3093049.0
8 1673632.75
9 1187463.0
10 943863.375
11 780190.3125
12 655626.125
13 556287.125
14 475354.65625
15 408733.0
16 353326.6875
17 307007.96875
18 267927.15625
19 234809.625
20 206592.0625
21 182432.09375
22 161623.21875
23 143620.015625
24 127988.7578125
25 114372.296875
26 102455.890625
27 91996.21875
28 82792.734375
29 74676.9375
30 67500.1953125
31 61129.06640625
32 55452.21875
33 50391.93359375
34 45868.70703125
35 41816.8515625
36 38178.37890625
37 34905.64453125
38 31958.1015625
39 29297.48828125
40 26890.44140625
41 24710.943359375
42 22734.94921875
43 20942.51953125
44 19312.505859375
45 17827.71875
46 16471.92578125
47 15233.986328125
48 14100.8759765625
49 13063.953125
50 12113.0068359375
51 11240.646484375
52 10439.3447265625
53 9702.345703125
54 9024.0556640625
55 8399.15625
56 7822.6865234375
57 7289.7529296875
58 6797.0615234375
59 6341.4560546875
60 5919.9931640625
61 5529

input 64, dimension 10維, hiden layer100維, 輸出10維

*   h = W_1X
*   a = max(0,h)
*   y_hat = W_2A





In [7]:
x

array([[ 1.05919669,  0.07113402, -2.03306471, ..., -1.21520003,
         0.37719864, -0.67541966],
       [-1.03297443, -0.77313845, -0.82435148, ...,  1.89997406,
        -0.8999344 ,  0.32798768],
       [ 1.06481935,  0.30444992,  1.35875659, ..., -1.74644885,
        -1.36549069, -0.71543064],
       ...,
       [ 0.90279429,  0.18236425, -0.07316246, ..., -0.57895163,
         2.06112284, -0.62786588],
       [-0.27995671,  0.42571184,  0.62596381, ...,  1.81871133,
        -2.1673964 ,  0.54723578],
       [ 0.45679073,  0.3080034 , -0.14603563, ...,  0.77715503,
        -0.02317651, -1.72492927]])

In [9]:
  h = x.dot(w1) # N * H
  h_relu = np.maximum(h, 0) # N * H
  y_pred = h_relu.dot(w2) # N * D_out

In [11]:
y_pred - y

array([[ 4.80438014e-07, -1.83965129e-06,  1.16126390e-07,
        -6.15046629e-06,  5.94865053e-06, -3.77769294e-06,
         2.44604280e-06,  2.14655436e-06,  3.14052944e-06,
        -5.02583330e-06],
       [ 1.05732503e-05, -5.13008777e-06,  1.39513785e-05,
        -1.22975669e-05,  3.18192644e-05, -1.23162373e-05,
         3.15291913e-06,  1.02155675e-05,  8.36306756e-06,
        -1.60961894e-05],
       [ 2.35103862e-06, -3.93865206e-06,  2.78855316e-06,
        -4.19644647e-06,  1.18413523e-05, -5.09090930e-06,
         5.16469827e-06,  5.78313381e-06,  3.66880883e-06,
        -6.51733451e-06],
       [ 2.80897765e-06, -1.52807128e-07, -4.88023974e-07,
         1.11148357e-06,  1.76903988e-06,  1.18588547e-07,
         6.84761074e-07,  8.05711055e-07, -4.19814456e-07,
        -5.88018349e-07],
       [ 7.92495196e-06, -9.71140211e-06,  6.85894507e-06,
        -7.75885722e-06,  1.77465534e-05, -9.32376520e-06,
         5.70848230e-06,  7.14627593e-06,  7.93726870e-06,
        -1.

In [8]:
y

array([[-1.4273267 ,  0.83320644, -0.32601741,  0.92974528,  1.36627367,
         0.05080788,  1.0403592 , -1.33162891, -0.21919757,  1.73814064],
       [-0.55760061, -0.23568743, -0.49497438,  0.0070339 , -0.01267485,
         0.8814321 , -1.34163768,  0.37969833,  0.97074497, -1.50765958],
       [-1.37748647, -0.1626403 , -1.222668  , -1.83951345,  0.83677149,
         2.65543075,  0.32745036,  0.05206815,  1.0242805 , -0.61652511],
       [ 1.51196182, -0.74806355,  0.22946631, -0.58856846,  0.08246245,
        -0.70553323, -1.96361275,  1.2722481 ,  0.42728174,  0.18496758],
       [ 0.71404033,  0.71842481,  0.0294637 ,  0.09295476, -0.66026435,
         0.61384573, -1.12138657,  1.38353561,  0.69985647, -1.54040365],
       [-1.19139777,  0.99156205,  1.2579349 , -1.58271786,  0.14544608,
         0.85728809, -1.57304843,  0.77507161,  1.86498481,  0.22399471],
       [-0.06601737,  0.78320314, -0.6086617 ,  0.28510474, -0.46198933,
         0.69674965,  1.0084822 ,  0.15337778